In [2]:
import numpy as np
import matplotlib.pyplot as plt

# Echauffement

a = np.array([1, 2, 3])

#print(a)
#print(a.shape)

#print(a[:,None])
#print(a[:,None].shape)

#print(a[None,:])
#print(a[None,:].shape)

b = np.arange(6).reshape(2,3)
#print(b)
#print(b[:,None,:])
#print(b.shape)
#print(b[:,:,None])

#Bilan: le None "empaquette" ce qui suit dans des crochets qui ne contiennent qu'un élement: la suite.

In [3]:
# Initialisation aléatoire

# les bornes pour le tirage au sort initial
mass_max = 3.
    
x_min, x_max = -10., 10.
y_min, y_max = -10., 10.

speed_max = 1.

def init_problem(N):
    """
    retourne un tuple masses, positions, speeds
    de formes resp.   (N,)    (2, N)     (2, N)
    tiré au sort dans les bornes définies ci-dessus
    """
    infpos=np.array([x_min,y_min]).reshape((2,1)) #Il faut un vecteur colonne
    suppos=np.array([x_max,y_max]).reshape((2,1)) #car les bornes inf et sup varient selon la 2e dimension du tableau random créé
    
    Masses=np.random.uniform(mass_max*0.01,mass_max,N)
    Positions=np.random.uniform(infpos,suppos,(2,N))

    
    infspeed=np.array([speed_max*0.01,speed_max*0.01]).reshape((2,1))
    supspeed=np.array([speed_max,speed_max]).reshape((2,1))

    Speeds=np.random.uniform(infspeed,supspeed,(2,N))
    

    return Masses,Positions,Speeds

masses, positions, speeds = init_problem(10)
try:
    assert masses.shape == (10,) and positions.shape == speeds.shape == (2, 10)
    print("OK")
except:
    print("nope")

#->OK



OK


In [4]:
# Initialisation reproductible

# for your convenience

def init3():
    # first element is sun-like: heavy, at the center, and no speed
    masses = np.array([3, 1, 1], dtype=float)
    positions = np.array([
        [0, 5, -5], 
        [0, 1, -1]], dtype=float)
    speeds = np.array([
        [0, -1, 1], 
        [0, 0, 0]], dtype=float)
    return masses, positions, speeds


In [17]:
# Les forces


def forces(masses, positions, N, G=1.0):
    """
    returns an array of shape (2,N)
    that contains the force felt by each mass from all the others
    G is the Newton constant and by default is set to 1 
    (we have abstract units anyway)
    """
    # Etape 1
    diff=positions[:,:,None] - positions[:,None,:]
        # Ici on broadcast en étendant les lignes puis les colonnes 
    # Etape 2
    dist=np.linalg.norm(diff,axis=2)
    # Etape 3
    gmimj=masses[:,None]*masses[None,:]*G
    # Etape 4
    quotientij=diff/(dist[:,None,:]**3)
    force=gmimj[None,:,:]*quotientij
    force_par_recepteur=np.sum(force,axis=1)
    return force_par_recepteur


# print(forces(init3()[0],init3()[1],3))
# Sur la diagonale, les forces valent 0 grâce aux différences nulles 
# Donc on peut sommer sans se poser de question pour la diagonale
# On obtient bien un tableau de 2 lignes, 3 colonnes, contenant les Fx et Fy subies par les masses-réceptrices




In [ ]:
# Simulateur

def simulate(masses, positions, speeds, dt=0.1, nb_steps=100):
    """
    should return the positions across time
    so an array of shape (nb_steps, dim, N)
    optional dt is the time step
    """
    #Initialisation
    dim=np.shape(positions)[0]
    N=np.shape(positions)[1]
    Res=np.empty((nb_steps,dim,N))
    Positions=positions.copy()
    Speeds=speeds.copy()

    for i_t in range(nb_steps):
        Res[i_t,:,:]=Positions
        #Partant des positions et masses, on calcule les forces, puis les accélérations
        Forces=forces(masses,Positions,N)
        a=Forces/masses
        #L'"intégration" donne les nouvelles vitesses en vigueur à la prochaine boucle
        Speeds=Speeds+(a*dt)
        #L'"intégration" donne les nouvelles positions à ajouter au Res à la prochaine boucle
        Positions=Positions+(Speeds*dt)

    return Res

# pour tester

SMALL_STEPS = 4

masses, positions, speeds=init3()
s = simulate(masses, positions, speeds, nb_steps=SMALL_STEPS)

#print(s)

#if s.shape == (SMALL_STEPS, 2, 3):
    #print("shape OK")


[[[ 0.          5.         -5.        ]
  [ 0.          1.         -1.        ]]

 [[ 0.          4.89982111 -4.89982111]
  [ 0.          0.99552786 -0.99552786]]

 [[ 0.          4.79945595 -4.79945595]
  [ 0.          0.98654332 -0.98654332]]

 [[ 0.          4.69889665 -4.69889665]
  [ 0.          0.97296381 -0.97296381]]]
shape OK


In [ ]:
# votre code

def draw(simulation, masses, colors=None, scale=10.):
    """
    takes as input the result of simulate() above,
    and draws the nb_steps positions of each of the N bodies
    ideally it should return a matplotlib Axes object

    one can provide a collection of N colors to use for each body
    if not provided this is randomized

    also the optional scale parameter is used as a constant
    multiplier to obtain the final size of each dot on the figure
    """
    pass
